### ISSUE TITLE
Migration tools Libcrypto++ pkg-name instead of libcryptopp

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [magiruuvelvet/OTPGen#4]
# Issue template
Same issue as in pull request 3 but in Migration Tool's CMakeLists.txt file

 - [ ] Operating System
 - [ ] Compiler
 - [ ] CMake version
 - [x] CMake build options used and the console output
 - [ ] When using the GUI: version of Qt
 - [ ] zlib: bundled or shared
 - [ ] QR Code Support enabled?

 - [ ] A description of the issue
 - [ ] If possible, how to reproduce the problem

https://github.com/SCOTT-HAMILTON/OTPGen/blob/fix-libcrypto%2B%2B-to-libcryptopp/Source/MigrationTool/CMakeLists.txt#L31

**Comment by magiruuvelvet** [comment]
fixed
